apiVersion: apps/v1
kind: Deployment
metadata:
    name: podinfo-blue
    namespace: test
    labels:
        app: podinfo
        version: blue
spec:
    replicas: 2
    selector:
        matchLabels:
            app: podinfo
            version: blue
    template:
        metadata:
            labels:
                app: podinfo
                version: blue
        spec:
            containers:
                - name: app-container
                  image: ghcr.io/stefanprodan/podinfo:6.7.1
                  env:
                      - name: PODINFO_UI_COLOR
                        value: "blue" # Blue environment color

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: podinfo-green
    namespace: test
    labels:
        app: podinfo
        version: green
spec:
    replicas: 2
    selector:
        matchLabels:
            app: podinfo
            version: green
    template:
        metadata:
            labels:
                app: podinfo
                version: green
        spec:
            containers:
                - name: app-container
                  image: ghcr.io/stefanprodan/podinfo:6.7.1
                  env:
                      - name: PODINFO_UI_COLOR
                        value: "green" # Green environment color

---
apiVersion: v1
kind: Service
metadata:
    name: podinfo-blue
    namespace: test
spec:
    selector:
        app: podinfo
        version: blue
    ports:
        - protocol: TCP
          port: 80
          targetPort: 9898
    type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
    name: podinfo-green
    namespace: test
spec:
    selector:
        app: podinfo
        version: green
    ports:
        - protocol: TCP
          port: 80
          targetPort: 9898
    type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: podinfo-ingress
    namespace: test
spec:
    ingressClassName: nginx
    rules:
        - host:
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: podinfo-green # change this for switch
                            port:
                                number: 80
