apiVersion: v1
kind: Secret
metadata:
    name: httpd-secret
    namespace: test
type: Opaque
data:
    password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Pod
metadata:
    name: simple-httpd
    namespace: test
spec:
    containers:
        - name: httpd
          image: httpd
          ports:
              - containerPort: 80
          env:
              - name: CUSTOM_SECRET_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: httpd-secret
                        key: password
          volumeMounts:
              - name: secret-volume
                mountPath: /etc/secret
    volumes:
        - name: secret-volume
          secret:
              secretName: httpd-secret
