# Validierung mit kubectl auth can-i get configmaps --as=system:serviceaccount:test:configmap-reader -n test
apiVersion: v1
kind: ServiceAccount
metadata:
    name: configmap-reader
    namespace: test

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: test
    name: configmap-reader
rules:
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: configmap-reader-binding
    namespace: test
subjects:
    - kind: ServiceAccount
      name: configmap-reader
      namespace: test
roleRef:
    kind: Role
    name: configmap-reader
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: httpd-config
    namespace: test
data:
    test: test-value

---
apiVersion: v1
kind: Pod
metadata:
    name: simple-httpd
    namespace: test
spec:
    serviceAccountName: configmap-reader
    containers:
        - name: httpd
          image: httpd
          ports:
              - containerPort: 80
